# -*- coding: utf-8 -*-
"""ejemplo1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uNOhE9ARNJA_tYB360oUwSs3c6H98FTY
"""

import streamlit as st
st.write('Hello, *World!* :sunglasses:')